when@dev: &dev
    zenstruck_foundry:
        faker:
            locale: fr_FR
        persistence:
            # Flush only once per call of `PersistentObjectFactory::create()`
            flush_once: true

when@test: *dev
